spring:
  application:
    name: Tic-tac-toe
  main:
    banner-mode: 'OFF'
    web-application-type: none  
  profiles:
    active:
    - default
    
  aop:
    auto: false
  cache:
    type: simple
  task:
    execution:
      pool:
        core-size: 2
        max-size: 4
  jmx:
    enabled: false
